### ISSUE TITLE
Grace Period in subscription model

### ISSUE THREAD

**Issue by cappy99** [Labs64/NetLicensing-Community#42]
Where can I define how long the grace period is in the Subscription model? I am currently using community license.

**Comment by r-brown** [comment]
Hello @cappy99 you can enable the grace period for [Subscription](https://netlicensing.io/wiki/subscription) model on the module configuration page.
Simply enable "Grace Period" checkbox as follows:
<img width="1101" alt="Screenshot 2021-12-01 at 10 21 09" src="https://user-images.githubusercontent.com/1361258/144207893-908940f4-a21d-468d-9d49-1e06625da290.png">

**Comment by cappy99** [comment]
Thank you for your response. I understand how to turn on the grace period check box. 

However, this does not appear to change the "expires" property. How long is the grace period?  Can the grace time period be changed?  Do I need to upgrade my license to use this?

Thank you.

**Comment by r-brown** [comment]
There is no specific plan needed for grace period - this option is available for any time-volume licenses, such as Subscription.
Once you enabled a specific package as "grace", this will be added to the customer profile after main license expiration.
The length of the grace period is specified by the package marked as "Grace Period"

#### Product module configuration
<img width="1245" alt="grace-01" src="https://user-images.githubusercontent.com/1361258/144486922-4efb97a5-2911-4d5b-8883-72f7206e0966.png">

#### Grace Period license added
<img width="1088" alt="grace-02" src="https://user-images.githubusercontent.com/1361258/144486933-47888238-a131-44f9-a329-664c59a5343a.png">

**Comment by cappy99** [comment]
@r-brown thank you for the detailed response. This definitely answers my question. I was not including a separate grace package in my configuration.
